# Generated by Django 3.2.13 on 2022-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=120)),
                ('emp_email', models.CharField(max_length=120)),
                ('emp_designation', models.EmailField(max_length=254, unique=True)),
                ('emp_experince', models.PositiveIntegerField(default=0)),
                ('emp_salary', models.PositiveIntegerField()),
            ],
        ),
    ]
