# Generated by Django 3.2.13 on 2022-06-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220615_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_experince',
            new_name='emp_experience',
        ),
    ]
