# Generated by Django 3.2.13 on 2022-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_place',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
